// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drzkhnypirkyzxpsqdam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyemtobnlwaXJreXp4cHNxZGFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MTY2MDAsImV4cCI6MjA1NjE5MjYwMH0.1tx7PXO45E5tBXhE12JQiAIJsx2C04qwY8B3n8YHUoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);